parameters:
#    ctf_announcer.example.class: CTF\AnnouncerBundle\Example

services:
#    ctf_announcer.example:
#        class: %ctf_announcer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
