ctf_user_edit_profile:
    pattern:  /profile/edit
    defaults: { _controller: CTFUserBundle:User:editProfile }

ctf_get_edit_form:
    pattern: /profile/edit/form
    defaults: { _controller: CTFUserBundle:User:grabForm }
    options:
      expose: true

ctf_public_profile:
    pattern: /profile/show/{id}
    defaults: { _controller: CTFUserBundle:User:public }
    requirements:
      id: \d+
    options:
      expose: true