ctf_team_select:
    pattern:  /team/select
    defaults: { _controller: CTFTeamBundle:Team:select }
    options:
      expose: true

ctf_team_select_ajax:
    pattern:  /team/select/listen
    defaults: { _controller: CTFTeamBundle:Team:selectAjax }
    options:
      expose: true

ctf_team_select_action:
    pattern: /team/select/do
    defaults: { _controller: CTFTeamBundle:Team:selectTeam }
    
ctf_team_admin:
    pattern: /team/adminify
    defaults: { _controller: CTFTeamBundle:TeamAdmin:teamAdmin }

ctf_team_request_accept:
    pattern: /team/requests/accept/{tid}/{rid}
    defaults: { _controller: CTFTeamBundle:TeamAdmin:accept }

ctf_team_request_reject:
    pattern: /team/requests/reject/{tid}/{rid}
    defaults: { _controller: CTFTeamBundle:TeamAdmin:reject }

ctf_team_request_accept_admin:
    pattern: /team/requests/accept/adminify/{tid}/{rid}
    defaults: { _controller: CTFTeamBundle:TeamAdmin:acceptAsAdmin }

ctf_team_request_make_admin:
    pattern: /team/requests/make/adminify/{tid}/{rid}
    defaults: { _controller: CTFTeamBundle:TeamAdmin:makeAdmin }

ctf_team_status_update:
    pattern: /team/status/update/{status}
    defaults: { _controller: CTFTeamBundle:TeamAdmin:updateStatus }
    options:
      expose: true