parameters:
#    ctf_registration.example.class: CTF\RegistrationBundle\Example

services:
#    ctf_registration.example:
#        class: %ctf_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
