ctf_statistics_homepage:
    pattern:  /
    defaults: { _controller: CTFStatisticsBundle:Statistics:index }

ctf_statistics_genders_count:
    pattern: /stats/count/gender
    defaults: { _controller: CTFStatisticsBundle:Statistics:gendersCount }
    options:
      expose: true

ctf_statistics_team_count:
    pattern: /stats/count/team
    defaults: { _controller: CTFStatisticsBundle:Statistics:teamCount }
    options:
      expose: true

ctf_statistics_players_count:
    pattern: /stats/count/players
    defaults: { _controller: CTFStatisticsBundle:Statistics:totalPlayers }
    options:
      expose: true

ctf_statistics_nearby_users_pub:
    pattern: /stats/nearby/pub/{bounds}
    defaults: { _controller: CTFStatisticsBundle:Statistics:nearbyPub }
    options:
      expose: true

ctf_statistics_top_ten_orgs:
    pattern: /stats/top/ten/organizations
    defaults: { _controller: CTFStatisticsBundle:Statistics:topTenOrganizations }
    options:
      expose: true

ctf_statistics_bottom_ten_orgs:
    pattern: /stats/bottom/ten/organizations
    defaults: { _controller: CTFStatisticsBundle:Statistics:bottomTenOrganizations }
    options:
      expose: true

ctf_statistics_top_twenty_players:
    pattern: /esi/stats/top/twenty/players
    defaults: { _controller: CTFStatisticsBundle:Statistics:topTwentyPlayers }

ctf_statistics_bottom_twenty_players:
    pattern: /esi/stats/bottom/twenty/players
    defaults: { _controller: CTFStatisticsBundle:Statistics:bottomTwentyPlayers }