parameters:
#    ctf_statistics.example.class: CTF\StatisticsBundle\Example

services:
#    ctf_statistics.example:
#        class: %ctf_statistics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
