ctf_referral_register:
    pattern:  /refer/me/{ref}
    defaults: { _controller: CTFReferralBundle:Referral:register, ref: -1 }

ctf_referral_refer:
    pattern: /referree/{ref}
    defaults: { _controller: CTFReferralBundle:Referral:ref }
    
ctf_referral_shortify:
    pattern: /refer/link/shortify
    defaults: { _controller: CTFReferralBundle:Referral:shortenReferralLink }
    options:
      expose: true