ctf_quest_homepage:
    pattern:  /quest
    defaults: { _controller: CTFQuestBundle:Quest:dashboard }

ctf_quest_continue:
    pattern: /quest/continue
    defaults: { _controller: CTFQuestBundle:Quest:continueQuest }
    options:
      expose: true

ctf_quest_current:
    pattern: /quest/current/show
    defaults: { _controller: CTFQuestBundle:Quest:showCurrent }
    options:
      expose: true

ctf_quest_fetch:
    pattern: /quest/fetch/{qid}
    defaults: { _controller: CTFQuestBundle:Quest:fetchQuestion }
    options:
      expose: true

ctf_quest_hint:
    pattern: /quest/current/hint/{id}
    defaults: { _controller: CTFQuestBundle:Quest:grabHint }
    options:
      expose: true

ctf_quest_answer:
    pattern: /quest/current/answer/{id}
    defaults: { _controller: CTFQuestBundle:Quest:answer }
    options:
      expose: true
      
ctf_quest_rank:
    pattern: /quest/current/rank
    defaults: { _controller: CTFQuestBundle:Quest:rank }
    options:
      expose: true

ctf_quest_visit:
    pattern: /quest/visit/{filename}
    defaults: { _controller: CTFQuestBundle:Quest:visit }
    requirements:
      filename: ".+"

ctf_quest_finish:
    pattern: /quest/finish
    defaults: { _controller: CTFQuestBundle:Quest:finish }
    options:
      expose: true

ctf_quest_stoptoshare:
    pattern: /quest/stoptoshare/{next}
    defaults: { _controller: CTFQuestBundle:Quest:stopToShare }
    requirements:
      next: \d+
    options:
      expose: true

ctf_quest_share_cert:
    pattern: /quest/share/twitter
    defaults: { _controller: CTFQuestBundle:Quest:shareCertificateOnTwitter }

ctf_quest_counts_minar:
    pattern: /quest/minar/counts
    defaults: { _controller: CTFQuestBundle:Hack:minar }
    options:
      expose: true